version: '3.7'

services:
  backend:
    build:
      context: ./simple-api-student-main
      dockerfile: Dockerfile
    container_name: project_simpleapi
    networks:
    - app-network
    depends_on:
    - database
    ports:
      - "8080:8080"

  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name : post_gre_TP
    networks:
    - app-network

  httpd:
    build:
      context: ./devops-front-main
      dockerfile: Dockerfile
    container_name: front_final_simpleapi
    ports:
      - "8081:80"
    networks:
    - app-network
    depends_on:
    - backend

networks:
  app-network: