- name: Launch Proxy Container
  docker_container:
    name: front_final_simpleapi
    image: hugoepf/front_final_simpleapi:1.0
    pull: true
    state: started
    ports:
      - "80:80"
    networks:
      - name: app-network

  register: proxy_result


- name: Debug Proxy Container Result
  debug:
    var: proxy_result
